version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  db:
    image: mysql:latest
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Cambia esto por tu contraseña
      MYSQL_DATABASE: sales
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password  # Cambia esto por tu contraseña
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Asegúrate de que este archivo exista
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
